deploy:
  variables:
    PLUGIN_PATH: /deadline/
  tags:
    - cw-pvc
  script:
    - >
      rsync -rltvh --chown=nobody:nogroup --chmod=777 $CI_PROJECT_DIR/openpype/modules/deadline/repository/custom/plugins/* /deadline/custom/plugins/ &&
      rsync -rltvh --chown=nobody:nogroup --chmod=777 $CI_PROJECT_DIR/openpype/modules/deadline/repository/custom/plugins/GlobalJobPreLoad.py /deadline/custom/plugins/GlobalJobPreLoad.py
#rules:
#    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
