services:
  - name: docker:20.10.20-dind
    alias: docker

variables:
  # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
  DOCKER_TLS_CERTDIR: "/certs"

stages:
  - build
  - deploy
  - release

build-centos7:
  tags:
    - dind
  stage: build
  variables:
    BUILD_OS: centos7
  script:
    - apk add --no-cache bash
    - apk add --no-cache curl
    - apk add --no-cache python3
    - ./tools/docker_build.sh $BUILD_OS
    - version_command="import os;exec(open(os.path.join('./', 'openpype', 'version.py')).read());print('.'.join(__version__.split('.')[:2]));"
    - openpype_version="$(python3 -c "${version_command}")"
    - "tar -czvf ./build/openpype-${openpype_version}-${BUILD_OS}.tar.gz ./build"
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ./build/openpype-${openpype_version}-${BUILD_OS}.tar.gz "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/openpype/${openpype_version}/openpype-${openpype_version}-${BUILD_OS}.tar.gz"'
  when: manual
  rules:
    - if: '$CI_COMMIT_BRANCH == "release/alkemyx"'
      when: always
    - if: '$CI_COMMIT_BRANCH == "release/alkemyx-develop"'
      when: always

build-debian:
  tags:
    - dind
  stage: build
  variables:
    BUILD_OS: debian
  script:
    - apk add --no-cache bash
    - apk add --no-cache curl
    - apk add --no-cache python3
    - ./tools/docker_build.sh $BUILD_OS
    - version_command="import os;exec(open(os.path.join('./', 'openpype', 'version.py')).read());print('.'.join(__version__.split('.')[:2]));"
    - openpype_version="$(python3 -c "${version_command}")"
    - "tar -czvf ./build/openpype-${openpype_version}-${BUILD_OS}.tar.gz ./build"
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ./build/openpype-${openpype_version}-${BUILD_OS}.tar.gz "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/openpype/${openpype_version}/openpype-${openpype_version}-${BUILD_OS}.tar.gz"'
  when: manual
  rules:
    - if: '$CI_COMMIT_BRANCH == "release/alkemyx"'
      when: always
    - if: '$CI_COMMIT_BRANCH == "release/alkemyx-develop"'
      when: always

build-ubuntu20:
  tags:
    - dind
  stage: build
  variables:
    BUILD_OS: ubuntu20.04
  script:
    - apk add --no-cache bash
    - apk add --no-cache curl
    - apk add --no-cache python3
    # This build uses the unnamed Dockerfile, so we omit $BUILD_OS from the script call
    - ./tools/docker_build.sh
    - version_command="import os;exec(open(os.path.join('./', 'openpype', 'version.py')).read());print('.'.join(__version__.split('.')[:2]));"
    - openpype_version="$(python3 -c "${version_command}")"
    - "tar -czvf ./build/openpype-${openpype_version}-${BUILD_OS}.tar.gz ./build"
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ./build/openpype-${openpype_version}-${BUILD_OS}.tar.gz "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/openpype/${openpype_version}/openpype-${openpype_version}-${BUILD_OS}.tar.gz"'
  when: manual
  rules:
    - if: '$CI_COMMIT_BRANCH == "release/alkemyx"'
      when: always
    - if: '$CI_COMMIT_BRANCH == "release/alkemyx-develop"'
      when: always

build-ubuntu22:
  tags:
    - dind
  stage: build
  variables:
    BUILD_OS: ubuntu22.04
  script:
    - apk add --no-cache bash
    - apk add --no-cache curl
    - apk add --no-cache python3
    - ./tools/docker_build.sh $BUILD_OS
    - version_command="import os;exec(open(os.path.join('./', 'openpype', 'version.py')).read());print('.'.join(__version__.split('.')[:2]));"
    - openpype_version="$(python3 -c "${version_command}")"
    - "tar -czvf ./build/openpype-${openpype_version}-${BUILD_OS}.tar.gz ./build"
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ./build/openpype-${openpype_version}-${BUILD_OS}.tar.gz "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/openpype/${openpype_version}/openpype-${openpype_version}-${BUILD_OS}.tar.gz"'
  when: manual
  rules:
    - if: '$CI_COMMIT_BRANCH == "release/alkemyx"'
      when: always
    - if: '$CI_COMMIT_BRANCH == "release/alkemyx-develop"'
      when: always

build-patch:
  tags:
    - dind
  stage: build
  image: python:3.9
  script:
    - mkdir -p $CI_PROJECT_DIR/artifact/build
    # Proc dies after creating the poetry env on first run. Just run it twice
    - ./tools/create_zip.sh --path $CI_PROJECT_DIR/artifact/build
    - ./tools/create_zip.sh --path $CI_PROJECT_DIR/artifact/build
  artifacts:
    paths:
      - artifact
  when: manual
  allow_failure: false
  rules:
    - if: '$CI_COMMIT_BRANCH == "release/alkemyx"'
      when: always
    - if: '$CI_COMMIT_BRANCH == "release/alkemyx-develop"'
      when: always

deploy-patch:
  tags:
    - cw-pvc
  stage: deploy
  script:
    - cp -R ./artifact/build/* /pipe/openpype/versions/
    - chown -R 1000:776523089 /pipe/openpype/versions
  dependencies:
    - build-patch
  needs:
    - build-patch

patch-release:
  tags:
    - dind
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
    - apk add --no-cache python3
    - version_command="import os;exec(open(os.path.join('./', 'openpype', 'version.py')).read());print(__version__);"
    - openpype_version="$(python3 -c "${version_command}")"
    - release-cli create --description "Release ${openpype_version} using CI pipeline $CI_PIPELINE_ID" --tag-name "${openpype_version}"
  needs:
    - deploy-patch

deploy-to-deadline:
  tags:
    - cw-pvc
  stage: deploy
  script:
    - rsync -avh --chmod=777 --chown=nobody:nogroup $CI_PROJECT_DIR/openpype/modules/deadline/repository/custom/plugins/* /deadline-repo/custom/plugins/
  rules:
    - if: $CI_COMMIT_BRANCH == "release/alkemyx"'
      changes:
        - openpype/modules/deadline/repository/custom/plugins/**/*
