stages:
  - deploy

deploy-patch:
  tags:
    - cw-pvc
  stage: deploy
  script:
    - ./tools/create_zip.sh --path /pipe/openpype/versions/
  when: manual

deploy-minor:
  tags:
    - cw-pvc
  stage: deploy
  before_script:
    - version_command="import os;exec(open(os.path.join('$openpype_root', 'openpype', 'version.py')).read());print(__version__);" &&
    - export OPENPYPE_VERSION="$(python3 <<< ${version_command})" 
  script:
    - ./tools/docker_build.sh centos7
  after_script:
    - tar -czvf ./build/openpype-${OPENPYPE_VERSION}.tar.gz ./build/${OPENPYPE_VERSION}
    - curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ./build/openpype-${OPENPYPE_VERSION}.tar.gz "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/openpype/${OPENPYPE_VERSION}/openpype-${OPENPYPE_VERSION}.tar.gz"
  when: manual

deploy-to-deadline-repo:
  stage: deploy
  tags:
    - cw-pvc
  script:
    - >
      rsync -rltvhpog --chmod=777 --chown=nobody:nogroup --delete $CI_PROJECT_DIR/openpype/modules/deadline/repository/custom/plugins/* /deadline/custom/plugins/
  rules:
      - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
        changes:
          - openpype/modules/deadline/repository/custom/plugins/**/*
