stages:
  - deploy

deploy-patch:
  tags:
    - cw-pvc
  stage: deploy
  script:
    - ./tools/create_zip.sh --path /pipe/openpype/versions/
  when: manual

deploy-minor:
  tags:
    - dind
  stage: deploy
  script:
    - apk add --no-cache bash
    - ./tools/docker_build.sh centos7
    - >-
      version_command="import os;exec(open(os.path.join('$openpype_root', 'openpype', 'version.py')).read());print(__version__);" &&
      openpype_version="$(python3 <<< ${version_command})" &&
      tar -czvf ./build/openpype-${BUILD_VERSION}.tar.gz ./build/${BUILD_VERSION} &&
      curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ./build/openpype-${BUILD_VERSION}.tar.gz "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/openpype/${openpype_version}/openpype-${BUILD_VERSION}.tar.gz"
  when: manual

deploy-to-deadline-repo:
  stage: deploy
  tags:
    - cw-pvc
  script:
    - >
      rsync -rltvhpog --chmod=777 --chown=nobody:nogroup --delete $CI_PROJECT_DIR/openpype/modules/deadline/repository/custom/plugins/* /deadline/custom/plugins/
  rules:
      - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
        changes:
          - openpype/modules/deadline/repository/custom/plugins/**/*
